### ISSUE TITLE
Getting "Pass the NatInstanceProvider to a Vpc before accessing 'securityGroup'" even though I'm trying what it says.

### ISSUE THREAD

**Issue by ruckc** [AndrewGuenther/cdk-fck-nat#308]
With the below stack I get the `throw new Error('Pass the NatInstanceProvider to a Vpc before accessing \'securityGroup\'');` error.  Not sure what I am doing wrong.

```typescript
export class ExampleStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const natGatewayProvider = new FckNatInstanceProvider({
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T4G, ec2.InstanceSize.NANO),
    });

    const vpc = new ec2.Vpc(this, 'example-vpc', {
      natGatewayProvider,
      flowLogs: {
        vpcFlowLogs: {
          destination: ec2.FlowLogDestination.toCloudWatchLogs(),
          trafficType: ec2.FlowLogTrafficType.REJECT,
        }
      },
      ipAddresses: ec2.IpAddresses.cidr('10.0.0.0/16'),
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: 'example-public',
          subnetType: ec2.SubnetType.PUBLIC,
        },
        {
          cidrMask: 24,
          name: 'example-private',
          subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS,
        },
      ],
    });

    natGatewayProvider.securityGroup.addIngressRule(ec2.Peer.ipv4(vpc.vpcCidrBlock), ec2.Port.allTraffic());

    const cluster = new ecs.Cluster(this, 'example-cluster', {
      containerInsights: true,
      vpc: vpc,
    });
  }
}
```

**Comment by AndrewGuenther** [comment]
Could you share what version of CDK you're using?

**Comment by ruckc** [comment]
The latest - 2.133.0

**Comment by ruckc** [comment]
Not sure why, but if I change the logic to this...

```typescript
    for (const subnet of vpc.privateSubnets) {
      natGatewayProvider.securityGroup.addIngressRule(ec2.Peer.ipv4(subnet.ipv4CidrBlock), ec2.Port.allTraffic());
    }
```

I instead get this instead... which would mean it is "working" just not the example.

```
Error: Cannot retrieve value from context provider ami since account/region are not specified at the stack level. Configure "env" with an account and region when you define your stack.See https://docs.aws.amazon.com/cdk/latest/guide/environments.html for more details.
    at Function.getValue (/builds/user/example/node_modules/aws-cdk-lib/core/lib/context-provider.js:2:562)
    at LookupMachineImage.getImage (/builds/user/example/node_modules/aws-cdk-lib/aws-ec2/lib/machine-image/machine-image.js:1:16109)
    at new LaunchTemplate (/builds/user/example/node_modules/aws-cdk-lib/aws-ec2/lib/launch-template.js:1:4911)
    at FckNatInstanceProvider.configureNat (/builds/user/example/node_modules/cdk-fck-nat/src/index.ts:241:27)
    at Vpc.createNatGateways (/builds/user/example/node_modules/aws-cdk-lib/aws-ec2/lib/vpc.js:1:16591)
    at new Vpc (/builds/user/example/node_modules/aws-cdk-lib/aws-ec2/lib/vpc.js:1:14408)
    at new exampleStack (/builds/user/example/lib/example-stack.ts:21:17)
    at /builds/user/example/bin/example.ts:12:17
    at Object.<anonymous> (/builds/user/example/bin/example.ts:48:3)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
```

**Comment by ihortelanoarc** [comment]
I'm experiencing the same issue using `aws-cdk-lib` version 2.115.0

**Comment by AndrewGuenther** [comment]
@ruckc

>Error: Cannot retrieve value from context provider ami since account/region are not specified at the stack level. Configure "env" with an account and region when you define your stack.See https://docs.aws.amazon.com/cdk/latest/guide/environments.html for more details.

That issue can be fixed by following those instructions in the docs.

I've been unable to replicate this issue with any recent version of cdk. If anyone could link me to a minimum reproducible example repository I'll take a closer look.

**Comment by AndrewGuenther** [comment]
Closing this. Feel free to re-open with a link to an example repository.

**Comment by thehabbos007** [comment]
Not the original poster, but I ran into the same error when adding the `natGatewayProvider` to a cdk stack that already had been deployed. Not sue if that may be the reason.

I.e. first deploy 
```typescript
export class ExampleStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    const vpc = new ec2.Vpc(this, 'example-vpc',
      ipAddresses: ec2.IpAddresses.cidr('10.0.0.0/16'),
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: 'example-private',
          subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS,
        },
      ],
    });
 }
}
```

then update and deploy

```typescript
export class ExampleStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const natGatewayProvider = new FckNatInstanceProvider({
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T4G, ec2.InstanceSize.NANO),
    });

    const vpc = new ec2.Vpc(this, 'example-vpc', {
      natGatewayProvider,
      ipAddresses: ec2.IpAddresses.cidr('10.0.0.0/16'),
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: 'example-private',
          subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS,
        },
      ],
    });

    natGatewayProvider.securityGroup.addIngressRule(ec2.Peer.ipv4(vpc.vpcCidrBlock), ec2.Port.allTraffic());
 }
}
```

**Comment by thehabbos007** [comment]
If it can help anyone, I had set `natGateways: 0` before adding fck-nat in my VPC config, which threw the same error as the original report. Removing this fixed the issue
